version: '3.7'

services:

  web:
    build: ./web
    command: bash -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 web.asgi:application"
    volumes:
      - ./web/:/usr/src/web/
    ports:
      - 8000:8000
    env_file:
      - ./.env.docker
    depends_on:
      - celery
      - celery-beat
      - db

  celery:
    build: ./web
    command: celery -A web worker -Q accounts,celery -l INFO
    env_file:
      - ./.env.docker
    volumes:
      - ./web:/var/www/web
    links:
      - redis

  celery-beat:
    build: ./web
    command: celery -A web beat -l INFO
    env_file:
      - ./.env.docker
    volumes:
      - ./web:/var/www/web

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  redis:
    image: redis:latest

  bot:
    build: ./nemoobot
    command: python nemoobot.py
    volumes:
      - ./nemoobot/:/usr/src/nemoobot/
    env_file:
      - ./.env.docker
    depends_on:
      - web

volumes:
  postgres_data: