version: '3.7'

services:

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    command: bash -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 web.asgi:application"
    volumes:
      - static_volume:/home/app/web/staticfiles
    env_file:
      - ./.env.docker
    depends_on:
      - db

  celery:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    command: celery -A web worker -Q accounts,celery -l INFO
    env_file:
      - ./.env.docker
    links:
      - redis

  celery-beat:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    command: celery -A web beat -l INFO
    env_file:
      - ./.env.docker

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env.db

  redis:
    image: redis:latest

  bot:
    build:
      context: ./nemoobot
      dockerfile: Dockerfile.prod
    command: python nemoobot.py
    restart: always
    volumes:
      - ./nemoobot/:/usr/src/nemoobot/
    env_file:
      - ./.env.docker
    depends_on:
      - web

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/staticfiles/
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: