version: 2.1
jobs:
  test:
    docker:
      - image: circleci/python:3.8.6
    working_directory: ~/repo
    steps:
    - checkout
    - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --no-cache-dir --upgrade pip
            pip install --no-cache-dir -r ./nemoobot/requirements.txt
    - run:
        name: Tests
        command: |
         . venv/bin/activate
          python -m pytest ./nemoobot/bot -v

workflows:
  tests:
    jobs:
     - test