version: 2.1
jobs:
  build_test_image:docker:
    docker:
      - image: circleci/python:3.10
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build image for test
          command: |
            docker build -t samfrst/nemoobot-bot:$CIRCLE_SHA1 ./nemoobot/Dockerfile
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push samfrst/nemoobot-bot:$CIRCLE_SHA1
  bot_tests:
    docker:
      - image: samfrst/nemoobot-bot$CIRCLE_SHA1
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --no-cache-dir --upgrade pip
          pip install --no-cache-dir -r ./nemoobot/requirements.txt
    - run:
        name: run tests
        command: |
         . venv/bin/activate
          python -m pytest -vv

workflows:
  tests:
    jobs:
     - bot_tests