# Generated by Django 3.1.4 on 2021-01-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_connected_to_twitch',
            field=models.BooleanField(default=False),
        ),
    ]
